# Generated by Django 5.1.2 on 2024-10-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['day_of_week', 'shift', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], default='Morning', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week', 'shift')},
        ),
    ]
