# Generated by Django 5.1.2 on 2024-12-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='psid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
