# Generated by Django 5.1.2 on 2024-11-29 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappwebhook',
            name='conversation_state',
            field=models.CharField(choices=[('MENU', 'Main Menu'), ('NEW_QUERY', 'Creating New Query'), ('VIEW_QUERIES', 'Viewing Queries'), ('AWAITING_SUBJECT', 'Waiting for Subject'), ('AWAITING_DESCRIPTION', 'Waiting for Description')], default='MENU', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappwebhook',
            name='temp_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='whatsappwebhook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
