# Generated by Django 5.1.2 on 2024-11-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_whatsappwebhook_conversation_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookMessengerWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('message_body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_state', models.CharField(choices=[('MENU', 'Main Menu'), ('NEW_QUERY', 'Creating New Query'), ('VIEW_QUERIES', 'Viewing Queries'), ('AWAITING_SUBJECT', 'Waiting for Subject'), ('AWAITING_DESCRIPTION', 'Waiting for Description')], default='MENU', max_length=20)),
                ('temp_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Messenger Webhook',
                'verbose_name_plural': 'Facebook Messenger Webhooks',
            },
        ),
    ]
