# Generated by Django 5.1.2 on 2024-10-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0002_alter_query_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='priority',
            field=models.CharField(choices=[('A', 'High'), ('B', 'Medium'), ('C', 'Low')], default='B', max_length=1),
        ),
    ]
