# Generated by Django 5.1.2 on 2025-01-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reportexport',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportexport',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ReportCategory',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportExport',
        ),
    ]
