# Generated by Django 5.1.2 on 2024-11-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0003_alter_query_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='patient',
            new_name='user',
        ),
    ]
