# Generated by Django 5.1.2 on 2024-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0004_rename_patient_query_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='conversion_status',
            field=models.BooleanField(blank=True, help_text='Whether query led to appointment/conversion', null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='expected_response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='is_patient',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='query_type',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General Inquiry'), ('APPOINTMENT', 'Appointment Related'), ('TREATMENT', 'Treatment Related'), ('BILLING', 'Billing Related'), ('COMPLAINT', 'Complaint'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='resolution_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
