# Generated by Django 5.1.2 on 2025-01-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancealert',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancealert',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_compliance_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceissue',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compliance_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceissue',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceissue',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_compliance_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancemetric',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_compliance_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancemetric',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancenote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereminder',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_compliance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceschedule',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to=models.Q(('role__name', 'PATIENT'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='assigned_compliance_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceschedule',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancenote',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='compliance_management.complianceschedule'),
        ),
        migrations.AddField(
            model_name='patientgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientgroup',
            name='patients',
            field=models.ManyToManyField(limit_choices_to={'role__name': 'PATIENT'}, related_name='compliance_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='compliancealert',
            index=models.Index(fields=['patient', 'alert_type', 'is_resolved'], name='compliance__patient_dcbe36_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancealert',
            index=models.Index(fields=['severity', 'is_resolved'], name='compliance__severit_df616f_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceissue',
            index=models.Index(fields=['patient', 'status'], name='compliance__patient_d992f3_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceissue',
            index=models.Index(fields=['severity', 'status'], name='compliance__severit_362ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancemetric',
            index=models.Index(fields=['patient', 'metric_type', 'evaluation_date'], name='compliance__patient_b79928_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereminder',
            index=models.Index(fields=['patient', 'reminder_type', 'status'], name='compliance__patient_210d19_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereminder',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='compliance__schedul_98e5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['report_type', 'generated_at'], name='compliance__report__cb4789_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['period_start', 'period_end'], name='compliance__period__f3f48f_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceschedule',
            index=models.Index(fields=['patient', 'status'], name='compliance__patient_8f19fe_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceschedule',
            index=models.Index(fields=['scheduled_date', 'status'], name='compliance__schedul_1f413d_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceschedule',
            index=models.Index(fields=['priority'], name='compliance__priorit_0a1fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancenote',
            index=models.Index(fields=['schedule', 'note_type'], name='compliance__schedul_856027_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancenote',
            index=models.Index(fields=['created_at'], name='compliance__created_ae5c37_idx'),
        ),
        migrations.AddIndex(
            model_name='patientgroup',
            index=models.Index(fields=['name', 'is_active'], name='compliance__name_b9d393_idx'),
        ),
    ]
