# Generated by Django 5.1.2 on 2025-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('UNPAID', 'Unpaid Leave'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('annual_allowance', models.PositiveIntegerField(help_text='Number of days allowed per year')),
                ('carry_forward_limit', models.PositiveIntegerField(default=0, help_text='Maximum days that can be carried forward to next year')),
                ('min_service_days', models.PositiveIntegerField(default=0, help_text='Minimum service days required before leave type becomes available')),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_documentation', models.BooleanField(default=False)),
                ('documentation_info', models.TextField(blank=True, help_text='Information about required documentation')),
                ('notice_period_days', models.PositiveIntegerField(default=0, help_text='Minimum notice period required in days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Leave Settings',
                'ordering': ['leave_type'],
            },
        ),
    ]
