# Generated by Django 5.1.2 on 2024-10-16 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GSTRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='paid_to',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='discount',
            new_name='cgst_amount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='tax',
            new_name='igst_amount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='issue_date',
            new_name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialreport',
            name='total_gst_collected',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialreport',
            name='total_tds_deducted',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_with_gst',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('NEFT', 'NEFT'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('NEFT', 'NEFT'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='financial_management.financialyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_management.gstrate'),
        ),
        migrations.CreateModel(
            name='TDSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds_rate', models.DecimalField(choices=[(0.1, '0.1%'), (1, '1%'), (2, '2%'), (5, '5%'), (10, '10%')], decimal_places=2, max_digits=4)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_deducted', models.DateField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_entries', to='financial_management.expense')),
            ],
        ),
    ]
