# Generated by Django 5.1.2 on 2025-01-02 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentform',
            name='procedure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_form', to='procedure_management.procedure'),
        ),
        migrations.AddField(
            model_name='procedureimage',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='procedure_management.procedure'),
        ),
        migrations.AddField(
            model_name='procedureresult',
            name='procedure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='procedure_management.procedure'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure_management.proceduretype'),
        ),
    ]
