# Generated by Django 5.1.2 on 2025-01-13 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0003_appointmentacknowledgement'),
        ('procedure_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='appointment_management.appointment'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='primary_doctor',
            field=models.ForeignKey(limit_choices_to={'role__name': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='primary_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='procedure_management.proceduretype'),
        ),
    ]
