# Generated by Django 5.1.2 on 2024-12-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('CHART', 'Chart'), ('TABLE', 'Table'), ('METRIC', 'Metric'), ('CUSTOM', 'Custom')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='JSON configuration for the widget')),
                ('position', models.PositiveIntegerField(help_text='Position of the widget in the dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('PATIENT', 'Patient Statistics'), ('FINANCIAL', 'Financial Summary'), ('APPOINTMENT', 'Appointment Analytics'), ('TREATMENT', 'Treatment Outcomes'), ('INVENTORY', 'Inventory Status'), ('HR', 'Human Resources'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('query', models.TextField(help_text='SQL query or aggregation logic for the report')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON object of report parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One-time')], max_length=20, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('IN_PROGRESS', 'In Progress')], max_length=20)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='report_results/')),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
