# Generated by Django 5.1.2 on 2025-01-15 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        ('reporting_and_analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='reportexecution',
            name='executed_by',
        ),
        migrations.RemoveField(
            model_name='reportexecution',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='report',
            name='next_run',
        ),
        migrations.RemoveField(
            model_name='report',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='report',
            name='query',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('moule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_categories', to='access_control.module')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reporting_and_analytics.reportcategory'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='report_exports/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reporting_and_analytics.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AnalyticsLog',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardWidget',
        ),
        migrations.DeleteModel(
            name='ReportExecution',
        ),
    ]
