# Generated by Django 5.1.2 on 2025-01-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_and_analytics', '0003_remove_dashboard_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcategory',
            old_name='moule',
            new_name='module',
        ),
    ]
