# Generated by Django 5.1.2 on 2024-12-18 18:19

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credential_type', models.CharField(choices=[('API_KEY', 'API Key'), ('ACCESS_TOKEN', 'Access Token'), ('SECRET_KEY', 'Secret Key'), ('USERNAME', 'Username'), ('PASSWORD', 'Password'), ('CERTIFICATE', 'Certificate'), ('JWT', 'JWT Token'), ('OAUTH', 'OAuth Credentials')], max_length=20)),
                ('service', models.CharField(help_text='Service these credentials are for', max_length=100)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20)),
                ('key', models.CharField(help_text='Credential identifier', max_length=100)),
                ('value', encrypted_model_fields.fields.EncryptedTextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional configuration or metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('SMTP', 'SMTP'), ('AWS_SES', 'Amazon SES'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('POSTMARK', 'Postmark'), ('CUSTOM', 'Custom SMTP')], max_length=50)),
                ('host', encrypted_model_fields.fields.EncryptedCharField()),
                ('port', models.IntegerField()),
                ('username', encrypted_model_fields.fields.EncryptedCharField()),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('encrypted_value', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted storage for sensitive values', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Setting Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SettingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('setting_type', models.CharField(choices=[('STRING', 'Text String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON Object'), ('EMAIL', 'Email Address'), ('URL', 'URL'), ('PASSWORD', 'Password'), ('FILE', 'File Path'), ('COLOR', 'Color Code'), ('DATETIME', 'Date and Time'), ('LIST', 'List of Values'), ('ENCRYPTED', 'Encrypted Value')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this setting contains sensitive information')),
                ('validation_regex', models.CharField(blank=True, help_text='Regular expression for validation', max_length=500)),
                ('validation_message', models.CharField(blank=True, max_length=200)),
                ('possible_values', models.JSONField(blank=True, help_text='List of possible values for LIST type settings', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('TWITTER', 'Twitter'), ('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube')], max_length=20)),
                ('app_id', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('app_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('webhook_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('verify_token', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('business_account_id', models.CharField(blank=True, max_length=200)),
                ('phone_number_id', models.CharField(blank=True, max_length=200)),
                ('additional_settings', models.JSONField(blank=True, help_text='Platform-specific additional settings', null=True)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
