# Generated by Django 5.1.2 on 2024-12-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_analyticsconfiguration_apiconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='allowed_file_extensions',
            field=models.JSONField(blank=True, default=list, help_text='Allowed file extensions for uploads', null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Business hours configuration', null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='holiday_calendar',
            field=models.JSONField(blank=True, default=list, help_text='Holiday calendar configuration', null=True),
        ),
    ]
