# Generated by Django 5.1.2 on 2024-10-16 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('INITIAL', 'Initial Consultation'), ('FOLLOW_UP', 'Follow-up Consultation'), ('EMERGENCY', 'Emergency Consultation'), ('TELE', 'Tele-consultation')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('chief_complaint', models.TextField()),
                ('vitals', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('diagnosis', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consultation_attachments/')),
                ('description', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consultation_management.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('reason', models.TextField()),
                ('tests_required', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_plan', to='consultation_management.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultation_management.consultation')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.medication')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle_changes', models.TextField(blank=True)),
                ('dietary_instructions', models.TextField(blank=True)),
                ('skincare_routine', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_instruction', to='consultation_management.consultation')),
            ],
        ),
    ]
