# Generated by Django 5.1.2 on 2024-12-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_management', '0005_consultation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='Care and precaution instructions'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lifestyle_instructions',
            field=models.TextField(blank=True, help_text='Lifestyle and dietary instructions for the patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_instructions',
            field=models.TextField(blank=True, help_text='Instructions for the patient to follow'),
        ),
    ]
