# Generated by Django 5.1.2 on 2024-10-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0004_appointment_affected_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='affected_area',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='treatment_method',
        ),
    ]
