# Generated by Django 5.1.2 on 2024-10-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0006_timeslotconfig_doctortimeslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up'), ('PROCEDURE', 'Procedure'), ('PHOTOTHERAPY', 'Phototherapy')], default='CONSULTATION', max_length=20),
        ),
    ]
