# Generated by Django 5.1.2 on 2024-11-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
