# Generated by Django 5.1.2 on 2024-12-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicstation',
            name='station_type',
            field=models.CharField(choices=[('ROOM', 'Treatment Room'), ('CONSULT', 'Consultation Room'), ('EXAM', 'Examination Room'), ('EQUIPMENT', 'Equipment Station'), ('OTHER', 'Other')], default='ROOM', max_length=20),
        ),
    ]
