# Generated by Django 5.1.2 on 2024-12-18 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_management', '0001_initial'),
        ('consultation_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicvisit',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_visit', to='consultation_management.consultation'),
        ),
    ]
