# Generated by Django 5.1.2 on 2025-01-15 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicvisit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicvisit',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitchecklist',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_management.clinicchecklist'),
        ),
        migrations.AddField(
            model_name='visitchecklist',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitchecklist',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='clinic_management.clinicvisit'),
        ),
        migrations.AddField(
            model_name='visitchecklistitem',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_management.checklistitem'),
        ),
        migrations.AddField(
            model_name='visitchecklistitem',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitchecklistitem',
            name='visit_checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic_management.visitchecklist'),
        ),
        migrations.AddField(
            model_name='clinicvisit',
            name='current_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='clinic_management.visitstatus'),
        ),
        migrations.AddField(
            model_name='visitstatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitstatuslog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic_management.visitstatus'),
        ),
        migrations.AddField(
            model_name='visitstatuslog',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='clinic_management.clinicvisit'),
        ),
        migrations.AlterUniqueTogether(
            name='visitchecklist',
            unique_together={('visit', 'checklist')},
        ),
        migrations.AlterUniqueTogether(
            name='visitchecklistitem',
            unique_together={('visit_checklist', 'checklist_item')},
        ),
        migrations.AddIndex(
            model_name='clinicvisit',
            index=models.Index(fields=['visit_date'], name='clinic_mana_visit_d_179a14_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicvisit',
            index=models.Index(fields=['visit_number'], name='clinic_mana_visit_n_3307b2_idx'),
        ),
    ]
