# Generated by Django 5.1.2 on 2024-12-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0002_clinicstation_station_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicstation',
            name='station_type',
        ),
    ]
