# Generated by Django 5.1.2 on 2024-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicvisit',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='clinicvisit',
            name='consultation',
        ),
    ]
