# Generated by Django 5.1.2 on 2024-12-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0003_remove_clinicstation_station_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitpaymenttransaction',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='visitpaymenttransaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='visitpaymenttransaction',
            name='visit',
        ),
        migrations.DeleteModel(
            name='PaymentTerminal',
        ),
        migrations.DeleteModel(
            name='VisitPaymentTransaction',
        ),
    ]
