# Generated by Django 5.1.2 on 2024-12-09 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phototherapy_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homephototherapylog',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phototherapyplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phototherapyplan',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='phototherapy_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homephototherapylog',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_logs', to='phototherapy_management.phototherapyplan'),
        ),
        migrations.AddField(
            model_name='phototherapyplan',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phototherapy_management.phototherapyprotocol'),
        ),
        migrations.AddField(
            model_name='phototherapysession',
            name='administered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phototherapysession',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='phototherapy_management.phototherapyplan'),
        ),
        migrations.AddField(
            model_name='phototherapyprotocol',
            name='phototherapy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phototherapy_management.phototherapytype'),
        ),
        migrations.AddField(
            model_name='phototherapydevice',
            name='phototherapy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phototherapy_management.phototherapytype'),
        ),
    ]
