# Generated by Django 5.1.2 on 2024-12-11 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phototherapy_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototherapysession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='phototherapy_management.phototherapydevice'),
        ),
    ]
