# Generated by Django 5.1.2 on 2025-01-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phototherapy_management', '0003_phototherapypayment_installment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototherapysession',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or comments about the session'),
        ),
    ]
