# Generated by Django 5.1.2 on 2024-12-11 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phototherapy_management', '0003_phototherapysession_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototherapysession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 11, 6, 14, 50, 26987, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phototherapysession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phototherapysession',
            name='compliance',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled'), ('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='phototherapysession',
            name='session_date',
            field=models.DateTimeField(),
        ),
    ]
