# Generated by Django 5.1.2 on 2024-12-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phototherapy_management', '0004_phototherapysession_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototherapysession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phototherapysession',
            name='device',
        ),
        migrations.RemoveField(
            model_name='phototherapysession',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='phototherapysession',
            name='compliance',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='phototherapysession',
            name='session_date',
            field=models.DateField(),
        ),
    ]
