# Generated by Django 5.1.2 on 2025-01-06 16:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phototherapy_management', '0004_phototherapysession_remarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhototherapyPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('number_of_sessions', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_featured', models.BooleanField(default=False, help_text='Featured packages are shown first in the list')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('therapy_type', models.ForeignKey(blank=True, help_text='Optional: Specific therapy type this package is for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phototherapy_management.phototherapytype')),
            ],
            options={
                'ordering': ['-is_featured', 'number_of_sessions'],
                'indexes': [models.Index(fields=['is_active', 'is_featured'], name='phototherap_is_acti_ebfd78_idx')],
            },
        ),
    ]
