# Generated by Django 5.1.2 on 2025-01-07 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phototherapy_management', '0005_phototherapypackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhototherapyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_hours', models.TextField(help_text="Describe the center's operating hours")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_devices', models.ManyToManyField(blank=True, related_name='centers', to='phototherapy_management.phototherapydevice')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='phototherapyplan',
            name='center',
            field=models.ForeignKey(blank=True, help_text='Select the phototherapy center where treatment will be administered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='phototherapy_management.phototherapycenter'),
        ),
        migrations.AddIndex(
            model_name='phototherapycenter',
            index=models.Index(fields=['is_active'], name='phototherap_is_acti_667398_idx'),
        ),
    ]
