# Generated by Django 5.1.2 on 2024-12-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phototherapy_management', '0005_remove_phototherapysession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototherapysession',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phototherapy_management.phototherapydevice'),
        ),
    ]
