# Generated by Django 5.1.2 on 2024-12-01 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_management', '0003_alter_consultation_patient'),
        ('image_management', '0002_alter_imageannotation_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientimage',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='consultation_management.consultation'),
        ),
        migrations.AddField(
            model_name='patientimage',
            name='tagged_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientimage',
            name='upload_type',
            field=models.CharField(choices=[('PROGRESS', 'Progress'), ('PROBLEM', 'Problem')], default='PROGRESS', max_length=10),
        ),
    ]
