# Generated by Django 5.1.2 on 2024-12-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_management', '0005_patientimage_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomparison',
            name='comparison_type',
            field=models.CharField(choices=[('individual', 'Individual Images'), ('consultation', 'Consultation Based')], default='individual', max_length=20),
        ),
    ]
